# 1. Read Libraries and Data

In [1]:
import pandas as pd
import numpy as np

import optuna
import tensorflow as tf

""" Sequential -  It allows you to create a model by simply adding layers one after another.
This is used for building simple neural networks where the flow of data is straightforward, 
from input to output, through a series of layers."""
from tensorflow.keras.models import Sequential

"""Dense is a fully connected layer, also known as a dense layer, in a neural network.
Each neuron in a dense layer receives input from all neurons in the previous layer."""
from tensorflow.keras.layers import Dense

"""Optimizers computes adaptive learning rates for each parameter"""
from tensorflow.keras.optimizers import SGD, Adam, RMSprop, Adagrad, Adadelta, Nadam

from sklearn.metrics import roc_auc_score

data = pd.read_csv('Employee.csv')

data

C:\Users\aksta\AppData\Local\Programs\Python\Python314\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0
1,Bachelors,2013,Pune,1,28,Female,No,3,1
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0
3,Masters,2016,Bangalore,3,27,Male,No,5,1
4,Masters,2017,Pune,3,24,Male,Yes,2,1
...,...,...,...,...,...,...,...,...,...
4648,Bachelors,2013,Bangalore,3,26,Female,No,4,0
4649,Masters,2013,Pune,2,37,Male,No,2,1
4650,Masters,2018,New Delhi,3,27,Male,No,5,1
4651,Bachelors,2012,Bangalore,3,30,Male,Yes,2,0
4652,Bachelors,2015,Bangalore,3,33,Male,Yes,4,0

# 2. Descriptive Statistics

In [2]:
data.describe(include='all')

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
count,4653,4653.000000,4653,4653.000000,4653.000000,4653,4653,4653.000000,4653.000000
unique,3,NaN,3,NaN,NaN,2,2,NaN,NaN
top,Bachelors,NaN,Bangalore,NaN,NaN,Male,No,NaN,NaN
freq,3601,NaN,2228,NaN,NaN,2778,4175,NaN,NaN
mean,NaN,2015.062970,NaN,2.698259,29.393295,NaN,NaN,2.905652,0.343864
std,NaN,1.863377,NaN,0.561435,4.826087,NaN,NaN,1.558240,0.475047
min,NaN,2012.000000,NaN,1.000000,22.000000,NaN,NaN,0.000000,0.000000
25%,NaN,2013.000000,NaN,3.000000,26.000000,NaN,NaN,2.000000,0.000000
50%,NaN,2015.000000,NaN,3.000000,28.000000,NaN,NaN,3.000000,0.000000
75%,NaN,2017.000000,NaN,3.000000,32.000000,NaN,NaN,4.000000,1.000000
max,NaN,2018.000000,NaN,3.000000,41.000000,NaN,NaN,7.000000,1.000000

# 3. Declare target and inputs and Split data using train_test_split

In [3]:
from sklearn.model_selection import train_test_split

inputs = data.drop('LeaveOrNot', axis=1)
target = data['LeaveOrNot']

X_train, X_test, y_train, y_test = train_test_split(inputs, target, test_size=0.2, random_state=42)

# 4. Using Label encoder convert categorics to numerical

In [4]:
from sklearn.preprocessing import LabelEncoder

encoders = {}
for i in X_train.select_dtypes(include=['object', 'string']).columns:
    le = LabelEncoder()
    X_train[i] = le.fit_transform(X_train[i])
    encoders[i] = le

for i in X_test.columns:
    if i in encoders:
        le = encoders[i]
        X_test[i] = le.transform(X_test[i])

display(X_train)
display(X_test)

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain
2850,1,2013,1,3,30,1,0,0
589,0,2012,0,3,25,1,0,3
2086,1,2017,2,2,29,1,0,2
445,1,2012,2,3,24,1,0,2
3654,1,2017,1,2,35,1,0,2
...,...,...,...,...,...,...,...,...
4426,0,2014,0,3,32,1,0,1
466,0,2013,0,3,26,1,1,4
3092,0,2016,0,3,39,0,0,1
3772,0,2015,0,3,41,1,0,1
860,0,2015,0,3,27,1,0,5

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain
297,0,2016,0,3,24,0,0,2
2705,0,2013,0,3,26,0,0,4
501,0,2017,1,2,25,0,0,3
1272,1,2015,2,2,28,0,0,2
3956,0,2012,0,3,33,1,0,1
...,...,...,...,...,...,...,...,...
3103,1,2017,1,1,40,1,0,5
733,0,2013,0,3,25,1,0,3
1419,0,2018,2,3,26,1,1,4
3291,0,2012,0,3,37,1,0,4
2178,0,2012,0,3,28,0,0,1

# 5. Scale inputs using StandartScaler

In [5]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# Fit only on training data
scaler.fit(X_train)

# Transform train and test
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Convert back to DataFrames
X_train_scaled = pd.DataFrame(
    X_train_scaled,
    columns=X_train.columns,
    index=X_train.index
)

X_test_scaled = pd.DataFrame(
    X_test_scaled,
    columns=X_test.columns,
    index=X_test.index
)

display(X_train_scaled)
display(X_test_scaled)

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain
2850,1.408598,-1.109740,0.252181,0.539424,0.117526,0.815674,-0.333731,-1.861550
589,-0.510436,-1.645675,-0.941990,0.539424,-0.914641,0.815674,-0.333731,0.061305
2086,1.408598,1.034001,1.446353,-1.226396,-0.088907,0.815674,-0.333731,-0.579646
445,1.408598,-1.645675,1.446353,0.539424,-1.121074,0.815674,-0.333731,-0.579646
3654,1.408598,1.034001,0.252181,-1.226396,1.149693,0.815674,-0.333731,-0.579646
...,...,...,...,...,...,...,...,...
4426,-0.510436,-0.573805,-0.941990,0.539424,0.530393,0.815674,-0.333731,-1.220598
466,-0.510436,-1.109740,-0.941990,0.539424,-0.708208,0.815674,2.996423,0.702257
3092,-0.510436,0.498065,-0.941990,0.539424,1.975427,-1.225980,-0.333731,-1.220598
3772,-0.510436,-0.037870,-0.941990,0.539424,2.388294,0.815674,-0.333731,-1.220598
860,-0.510436,-0.037870,-0.941990,0.539424,-0.501774,0.815674,-0.333731,1.343209

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain
297,-0.510436,0.498065,-0.941990,0.539424,-1.121074,-1.225980,-0.333731,-0.579646
2705,-0.510436,-1.109740,-0.941990,0.539424,-0.708208,-1.225980,-0.333731,0.702257
501,-0.510436,1.034001,0.252181,-1.226396,-0.914641,-1.225980,-0.333731,0.061305
1272,1.408598,-0.037870,1.446353,-1.226396,-0.295341,-1.225980,-0.333731,-0.579646
3956,-0.510436,-1.645675,-0.941990,0.539424,0.736827,0.815674,-0.333731,-1.220598
...,...,...,...,...,...,...,...,...
3103,1.408598,1.034001,0.252181,-2.992215,2.181861,0.815674,-0.333731,1.343209
733,-0.510436,-1.109740,-0.941990,0.539424,-0.914641,0.815674,-0.333731,0.061305
1419,-0.510436,1.569936,1.446353,0.539424,-0.708208,0.815674,2.996423,0.702257
3291,-0.510436,-1.645675,-0.941990,0.539424,1.562560,0.815674,-0.333731,0.702257
2178,-0.510436,-1.645675,-0.941990,0.539424,-0.295341,-1.225980,-0.333731,-1.220598

# 6. Create ANN model for classification use with best hyperparameters using Optuna

In [6]:
def create_model(trial):
    # Building artificial neural network
    model = Sequential()

     # we add 2 hidden layers and 1 output layer
    model.add(Dense(units=trial.suggest_int('units_layer1', 6, 32), activation='relu'))
    model.add(Dense(units=trial.suggest_int('units_layer2', 6, 32), activation='relu'))
    model.add(Dense(units=1, activation='sigmoid'))

    # Suggest hyperparameters for the optimizer
    optimizer_name = trial.suggest_categorical('optimizer', ['adam', 'sgd', 'rmsprop', 'adagrad'])
    learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 1e-2)
    
    if optimizer_name == 'adam':
        optimizer = Adam(learning_rate=learning_rate)
    elif optimizer_name == 'sgd':
        optimizer = SGD(learning_rate=learning_rate)
    elif optimizer_name == 'rmsprop':
        optimizer = RMSprop(learning_rate=learning_rate)
    elif optimizer_name == 'adagrad':
        optimizer = Adagrad(learning_rate=learning_rate)

    model.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['AUC'])
    
    return model

def optimal(trial):
    
    # Suggest the number of epochs and batch size
    epochs = trial.suggest_int('epochs', 10, 50)
    batch_size = trial.suggest_int('batch_size', 16, 64)
    
    model = create_model(trial)
    
    history = model.fit(X_train_scaled, y_train, epochs=epochs, batch_size=batch_size)
    
    y_pred = model.predict(X_test_scaled)
    score = roc_auc_score(y_test, y_pred)
    
    return score

study = optuna.create_study(direction='maximize')
study.optimize(optimal, n_trials=10)

print(f"Best trial: {study.best_trial.value}")
print(f"Best hyperparameters: {study.best_trial.params}")

best_params = study.best_trial.params

best_params

[I 2026-10-17 10:23:26,217] A new study created in memory with name: no-name-bcca2186-7c40-4bc4-93cc-9f8459457f08
C:\Users\aksta\AppData\Local\Temp\ipykernel_32492\1466992178.py:12: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 1e-2)

Epoch 1/29
83/83 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - AUC: 0.6930 - loss: 0.5828
Epoch 2/29
83/83 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7705 - loss: 0.5146
Epoch 3/29
83/83 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7980 - loss: 0.4833
Epoch 4/29
83/83 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8168 - loss: 0.4593
Epoch 5/29
83/83 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8282 - loss: 0.4422
Epoch 6/29
83/83 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8362 - loss: 0.4286
Epoch 7/29
83/83 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8427 - loss: 0.4178
Epoch 8/29
83/83 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8482 - loss: 0.4085
Epoch 9/29
83/83 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8526 - loss: 0.4009
Epoch 10/29
83/83 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8560 - loss: 0.3951
Epoch 11/29
83/83 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8590 - loss: 0.3906
Epoch 12/29
83/83 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8614 - loss: 0.3869
Epoch 13/29
83/83 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8636 - loss: 0.3841
Epoch 14/29
83/83 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8652 - loss: 0.3814
Epoch 15/29
83/83 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8667 - loss: 0.3790
Epoch 16/29
83/83 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8681 - loss: 0.3769
Epoch 17/29
83/83 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8693 - loss: 0.3751
Epoch 18/29
83/83 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8705 - loss: 0.3733
Epoch 19/29
83/83 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8714 - loss: 0.3717
Epoch 20/29
83/83 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8725 - loss: 0.3699
Epoch 21/29
83/83 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8736 - loss: 0.3684
Epoch 22/29
83/83 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8745 - loss: 0.3670
Epoch 23/29
83/83 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8755 - loss: 0.3654
Epoch 24/29
83/83 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8766 - loss: 0.3639
Epoch 25/29
83/83 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8775 - loss: 0.3628
Epoch 26/29
83/83 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8786 - loss: 0.3617
Epoch 27/29
83/83 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8793 - loss: 0.3610
Epoch 28/29
83/83 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8801 - loss: 0.3596
Epoch 29/29
83/83 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8808 - loss: 0.3588
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

[I 2026-10-17 10:23:31,464] Trial 0 finished with value: 0.8915836780552575 and parameters: {'epochs': 29, 'batch_size': 45, 'units_layer1': 16, 'units_layer2': 31, 'optimizer': 'rmsprop', 'learning_rate': 0.0035811641608295528}. Best is trial 0 with value: 0.8915836780552575.

Epoch 1/44

C:\Users\aksta\AppData\Local\Temp\ipykernel_32492\1466992178.py:12: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 1e-2)

89/89 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - AUC: 0.4098 - loss: 0.7068
Epoch 2/44
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.4110 - loss: 0.7057
Epoch 3/44
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.4122 - loss: 0.7045
Epoch 4/44
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.4135 - loss: 0.7034
Epoch 5/44
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.4152 - loss: 0.7024
Epoch 6/44
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.4168 - loss: 0.7013
Epoch 7/44
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 977us/step - AUC: 0.4182 - loss: 0.7003
Epoch 8/44
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 983us/step - AUC: 0.4189 - loss: 0.6992
Epoch 9/44
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 986us/step - AUC: 0.4207 - loss: 0.6982
Epoch 10/44
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.4224 - loss: 0.6972
Epoch 11/44
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.4236 - loss: 0.6963
Epoch 12/44
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.4246 - loss: 0.6953
Epoch 13/44
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 968us/step - AUC: 0.4265 - loss: 0.6943
Epoch 14/44
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.4283 - loss: 0.6934
Epoch 15/44
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.4297 - loss: 0.6925
Epoch 16/44
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.4315 - loss: 0.6916
Epoch 17/44
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 969us/step - AUC: 0.4324 - loss: 0.6907
Epoch 18/44
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.4337 - loss: 0.6898
Epoch 19/44
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.4359 - loss: 0.6889
Epoch 20/44
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.4379 - loss: 0.6881
Epoch 21/44
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.4396 - loss: 0.6872
Epoch 22/44
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.4411 - loss: 0.6864
Epoch 23/44
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.4423 - loss: 0.6856
Epoch 24/44
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.4447 - loss: 0.6848
Epoch 25/44
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.4458 - loss: 0.6840
Epoch 26/44
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.4475 - loss: 0.6832
Epoch 27/44
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.4493 - loss: 0.6824
Epoch 28/44
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.4505 - loss: 0.6817
Epoch 29/44
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.4527 - loss: 0.6809
Epoch 30/44
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.4549 - loss: 0.6802
Epoch 31/44
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.4570 - loss: 0.6795
Epoch 32/44
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 974us/step - AUC: 0.4581 - loss: 0.6787
Epoch 33/44
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.4593 - loss: 0.6780
Epoch 34/44
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.4610 - loss: 0.6773
Epoch 35/44
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.4627 - loss: 0.6766
Epoch 36/44
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.4651 - loss: 0.6759
Epoch 37/44
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.4662 - loss: 0.6752
Epoch 38/44
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.4673 - loss: 0.6746
Epoch 39/44
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.4692 - loss: 0.6739
Epoch 40/44
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.4711 - loss: 0.6733
Epoch 41/44
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.4731 - loss: 0.6726
Epoch 42/44
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.4750 - loss: 0.6720
Epoch 43/44
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.4765 - loss: 0.6713
Epoch 44/44
89/89 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.4779 - loss: 0.6707
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

[I 2026-10-17 10:23:37,852] Trial 1 finished with value: 0.4940963178591491 and parameters: {'epochs': 44, 'batch_size': 42, 'units_layer1': 24, 'units_layer2': 9, 'optimizer': 'sgd', 'learning_rate': 0.00017996979283064964}. Best is trial 0 with value: 0.8915836780552575.

Epoch 1/29

C:\Users\aksta\AppData\Local\Temp\ipykernel_32492\1466992178.py:12: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 1e-2)

80/80 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - AUC: 0.5514 - loss: 0.6925
Epoch 2/29
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.6329 - loss: 0.6279
Epoch 3/29
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.6847 - loss: 0.5935
Epoch 4/29
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7088 - loss: 0.5736
Epoch 5/29
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7241 - loss: 0.5610
Epoch 6/29
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7359 - loss: 0.5517
Epoch 7/29
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7459 - loss: 0.5442
Epoch 8/29
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7544 - loss: 0.5377
Epoch 9/29
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7619 - loss: 0.5319
Epoch 10/29
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7681 - loss: 0.5266
Epoch 11/29
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7734 - loss: 0.5216
Epoch 12/29
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7781 - loss: 0.5167
Epoch 13/29
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7823 - loss: 0.5121
Epoch 14/29
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7864 - loss: 0.5076
Epoch 15/29
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7900 - loss: 0.5032
Epoch 16/29
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7935 - loss: 0.4990
Epoch 17/29
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7968 - loss: 0.4950
Epoch 18/29
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7998 - loss: 0.4912
Epoch 19/29
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8026 - loss: 0.4875
Epoch 20/29
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8055 - loss: 0.4839
Epoch 21/29
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8080 - loss: 0.4805
Epoch 22/29
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8106 - loss: 0.4772
Epoch 23/29
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8131 - loss: 0.4740
Epoch 24/29
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8153 - loss: 0.4708
Epoch 25/29
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8175 - loss: 0.4678
Epoch 26/29
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8194 - loss: 0.4649
Epoch 27/29
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8213 - loss: 0.4621
Epoch 28/29
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8232 - loss: 0.4593
Epoch 29/29
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8251 - loss: 0.4566
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

[I 2026-10-17 10:23:42,843] Trial 2 finished with value: 0.8472549920841633 and parameters: {'epochs': 29, 'batch_size': 47, 'units_layer1': 22, 'units_layer2': 32, 'optimizer': 'adam', 'learning_rate': 0.00029936971243699933}. Best is trial 0 with value: 0.8915836780552575.

Epoch 1/48

C:\Users\aksta\AppData\Local\Temp\ipykernel_32492\1466992178.py:12: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 1e-2)

60/60 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - AUC: 0.6212 - loss: 0.6318
Epoch 2/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7228 - loss: 0.5622
Epoch 3/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7578 - loss: 0.5365
Epoch 4/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7745 - loss: 0.5203
Epoch 5/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7858 - loss: 0.5075
Epoch 6/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7959 - loss: 0.4956
Epoch 7/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8050 - loss: 0.4846
Epoch 8/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8129 - loss: 0.4743
Epoch 9/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8193 - loss: 0.4653
Epoch 10/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8257 - loss: 0.4573
Epoch 11/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8311 - loss: 0.4502
Epoch 12/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8359 - loss: 0.4435
Epoch 13/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8398 - loss: 0.4374
Epoch 14/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8435 - loss: 0.4319
Epoch 15/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8467 - loss: 0.4267
Epoch 16/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8491 - loss: 0.4220
Epoch 17/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8515 - loss: 0.4177
Epoch 18/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8538 - loss: 0.4134
Epoch 19/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8559 - loss: 0.4093
Epoch 20/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8576 - loss: 0.4057
Epoch 21/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8594 - loss: 0.4024
Epoch 22/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8609 - loss: 0.3994
Epoch 23/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8627 - loss: 0.3964
Epoch 24/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8642 - loss: 0.3937
Epoch 25/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8658 - loss: 0.3911
Epoch 26/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8671 - loss: 0.3886
Epoch 27/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8684 - loss: 0.3864
Epoch 28/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8696 - loss: 0.3842
Epoch 29/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8704 - loss: 0.3823
Epoch 30/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8715 - loss: 0.3804
Epoch 31/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8724 - loss: 0.3787
Epoch 32/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8731 - loss: 0.3771
Epoch 33/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8741 - loss: 0.3755
Epoch 34/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8750 - loss: 0.3740
Epoch 35/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8758 - loss: 0.3726
Epoch 36/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8765 - loss: 0.3713
Epoch 37/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8770 - loss: 0.3701
Epoch 38/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8777 - loss: 0.3690
Epoch 39/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8783 - loss: 0.3679
Epoch 40/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8791 - loss: 0.3668
Epoch 41/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8797 - loss: 0.3659
Epoch 42/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8801 - loss: 0.3650
Epoch 43/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8805 - loss: 0.3640
Epoch 44/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8810 - loss: 0.3632
Epoch 45/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8815 - loss: 0.3623
Epoch 46/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8823 - loss: 0.3614
Epoch 47/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8826 - loss: 0.3607
Epoch 48/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8831 - loss: 0.3599
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

[I 2026-10-17 10:23:49,328] Trial 3 finished with value: 0.8919871303814922 and parameters: {'epochs': 48, 'batch_size': 63, 'units_layer1': 29, 'units_layer2': 13, 'optimizer': 'adam', 'learning_rate': 0.0013669388891433209}. Best is trial 3 with value: 0.8919871303814922.

Epoch 1/38

C:\Users\aksta\AppData\Local\Temp\ipykernel_32492\1466992178.py:12: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 1e-2)

162/162 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - AUC: 0.6206 - loss: 0.6779
Epoch 2/38
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.6222 - loss: 0.6721
Epoch 3/38
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.6239 - loss: 0.6669
Epoch 4/38
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.6255 - loss: 0.6620
Epoch 5/38
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.6275 - loss: 0.6575
Epoch 6/38
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.6295 - loss: 0.6534
Epoch 7/38
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.6314 - loss: 0.6497
Epoch 8/38
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 972us/step - AUC: 0.6331 - loss: 0.6462
Epoch 9/38
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.6351 - loss: 0.6431
Epoch 10/38
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 995us/step - AUC: 0.6368 - loss: 0.6402
Epoch 11/38
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.6386 - loss: 0.6375
Epoch 12/38
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.6400 - loss: 0.6351
Epoch 13/38
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.6421 - loss: 0.6328
Epoch 14/38
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.6434 - loss: 0.6307
Epoch 15/38
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.6455 - loss: 0.6288
Epoch 16/38
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.6470 - loss: 0.6270
Epoch 17/38
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.6483 - loss: 0.6254
Epoch 18/38
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.6497 - loss: 0.6239
Epoch 19/38
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 968us/step - AUC: 0.6512 - loss: 0.6225
Epoch 20/38
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 971us/step - AUC: 0.6529 - loss: 0.6212
Epoch 21/38
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 993us/step - AUC: 0.6538 - loss: 0.6199
Epoch 22/38
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.6553 - loss: 0.6188
Epoch 23/38
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.6569 - loss: 0.6177
Epoch 24/38
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.6583 - loss: 0.6167
Epoch 25/38
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 977us/step - AUC: 0.6595 - loss: 0.6157
Epoch 26/38
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.6606 - loss: 0.6148
Epoch 27/38
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.6617 - loss: 0.6139
Epoch 28/38
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.6630 - loss: 0.6131
Epoch 29/38
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.6646 - loss: 0.6123
Epoch 30/38
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.6654 - loss: 0.6116
Epoch 31/38
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.6667 - loss: 0.6108
Epoch 32/38
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.6683 - loss: 0.6101
Epoch 33/38
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 990us/step - AUC: 0.6692 - loss: 0.6094
Epoch 34/38
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.6702 - loss: 0.6087
Epoch 35/38
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.6713 - loss: 0.6081
Epoch 36/38
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 988us/step - AUC: 0.6724 - loss: 0.6074
Epoch 37/38
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.6738 - loss: 0.6068
Epoch 38/38
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.6751 - loss: 0.6062
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

[I 2026-10-17 10:23:58,027] Trial 4 finished with value: 0.7011746080384046 and parameters: {'epochs': 38, 'batch_size': 23, 'units_layer1': 6, 'units_layer2': 17, 'optimizer': 'adam', 'learning_rate': 1.8450671324211073e-05}. Best is trial 3 with value: 0.8919871303814922.

Epoch 1/24

C:\Users\aksta\AppData\Local\Temp\ipykernel_32492\1466992178.py:12: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 1e-2)

104/104 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - AUC: 0.5908 - loss: 0.7524
Epoch 2/24
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.6022 - loss: 0.6831
Epoch 3/24
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.6271 - loss: 0.6392
Epoch 4/24
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.6590 - loss: 0.6059
Epoch 5/24
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.6915 - loss: 0.5822
Epoch 6/24
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7116 - loss: 0.5666
Epoch 7/24
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7259 - loss: 0.5559
Epoch 8/24
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7366 - loss: 0.5477
Epoch 9/24
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7455 - loss: 0.5407
Epoch 10/24
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7532 - loss: 0.5346
Epoch 11/24
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7595 - loss: 0.5288
Epoch 12/24
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7649 - loss: 0.5236
Epoch 13/24
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7691 - loss: 0.5189
Epoch 14/24
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7726 - loss: 0.5148
Epoch 15/24
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7760 - loss: 0.5110
Epoch 16/24
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7785 - loss: 0.5076
Epoch 17/24
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7805 - loss: 0.5045
Epoch 18/24
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7825 - loss: 0.5018
Epoch 19/24
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7842 - loss: 0.4993
Epoch 20/24
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7857 - loss: 0.4970
Epoch 21/24
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7871 - loss: 0.4950
Epoch 22/24
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7884 - loss: 0.4932
Epoch 23/24
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7895 - loss: 0.4915
Epoch 24/24
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7906 - loss: 0.4899
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

[I 2026-10-17 10:24:03,012] Trial 5 finished with value: 0.8186711608191615 and parameters: {'epochs': 24, 'batch_size': 36, 'units_layer1': 6, 'units_layer2': 32, 'optimizer': 'adam', 'learning_rate': 0.00034389474894306346}. Best is trial 3 with value: 0.8919871303814922.

Epoch 1/42

C:\Users\aksta\AppData\Local\Temp\ipykernel_32492\1466992178.py:12: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 1e-2)

162/162 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - AUC: 0.4892 - loss: 0.8347
Epoch 2/42
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.4903 - loss: 0.8302
Epoch 3/42
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 941us/step - AUC: 0.4916 - loss: 0.8258
Epoch 4/42
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.4928 - loss: 0.8216
Epoch 5/42
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.4940 - loss: 0.8174
Epoch 6/42
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.4951 - loss: 0.8134
Epoch 7/42
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.4965 - loss: 0.8095
Epoch 8/42
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 976us/step - AUC: 0.4977 - loss: 0.8057
Epoch 9/42
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.4993 - loss: 0.8021
Epoch 10/42
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.5000 - loss: 0.7985
Epoch 11/42
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 982us/step - AUC: 0.5013 - loss: 0.7950
Epoch 12/42
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.5025 - loss: 0.7917
Epoch 13/42
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 972us/step - AUC: 0.5037 - loss: 0.7884
Epoch 14/42
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.5045 - loss: 0.7852
Epoch 15/42
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.5062 - loss: 0.7821
Epoch 16/42
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.5064 - loss: 0.7791
Epoch 17/42
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.5083 - loss: 0.7762
Epoch 18/42
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 951us/step - AUC: 0.5090 - loss: 0.7734
Epoch 19/42
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 928us/step - AUC: 0.5097 - loss: 0.7706
Epoch 20/42
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.5109 - loss: 0.7679
Epoch 21/42
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 919us/step - AUC: 0.5117 - loss: 0.7652
Epoch 22/42
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.5130 - loss: 0.7627
Epoch 23/42
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.5136 - loss: 0.7601
Epoch 24/42
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.5152 - loss: 0.7577
Epoch 25/42
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.5155 - loss: 0.7553
Epoch 26/42
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.5164 - loss: 0.7529
Epoch 27/42
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.5179 - loss: 0.7506
Epoch 28/42
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.5185 - loss: 0.7484
Epoch 29/42
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.5198 - loss: 0.7462
Epoch 30/42
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.5205 - loss: 0.7441
Epoch 31/42
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.5216 - loss: 0.7420
Epoch 32/42
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.5222 - loss: 0.7400
Epoch 33/42
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.5232 - loss: 0.7380
Epoch 34/42
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.5240 - loss: 0.7361
Epoch 35/42
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.5247 - loss: 0.7342
Epoch 36/42
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.5257 - loss: 0.7323
Epoch 37/42
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.5264 - loss: 0.7305
Epoch 38/42
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.5278 - loss: 0.7288
Epoch 39/42
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.5283 - loss: 0.7271
Epoch 40/42
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.5287 - loss: 0.7254
Epoch 41/42
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.5299 - loss: 0.7237
Epoch 42/42
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.5306 - loss: 0.7221
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

[I 2026-10-17 10:24:12,788] Trial 6 finished with value: 0.5024819978550635 and parameters: {'epochs': 42, 'batch_size': 23, 'units_layer1': 16, 'units_layer2': 8, 'optimizer': 'sgd', 'learning_rate': 8.4757884568933e-05}. Best is trial 3 with value: 0.8919871303814922.

Epoch 1/30

C:\Users\aksta\AppData\Local\Temp\ipykernel_32492\1466992178.py:12: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 1e-2)

65/65 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - AUC: 0.6179 - loss: 0.6369
Epoch 2/30
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7228 - loss: 0.5740
Epoch 3/30
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7473 - loss: 0.5499
Epoch 4/30
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7633 - loss: 0.5336
Epoch 5/30
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7758 - loss: 0.5201
Epoch 6/30
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7858 - loss: 0.5084
Epoch 7/30
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7950 - loss: 0.4979
Epoch 8/30
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8038 - loss: 0.4882
Epoch 9/30
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8116 - loss: 0.4788
Epoch 10/30
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8185 - loss: 0.4703
Epoch 11/30
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8240 - loss: 0.4629
Epoch 12/30
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8284 - loss: 0.4565
Epoch 13/30
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8329 - loss: 0.4506
Epoch 14/30
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8365 - loss: 0.4452
Epoch 15/30
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8402 - loss: 0.4402
Epoch 16/30
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8431 - loss: 0.4356
Epoch 17/30
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8458 - loss: 0.4314
Epoch 18/30
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8482 - loss: 0.4273
Epoch 19/30
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8506 - loss: 0.4236
Epoch 20/30
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8524 - loss: 0.4202
Epoch 21/30
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8543 - loss: 0.4170
Epoch 22/30
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8557 - loss: 0.4141
Epoch 23/30
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8572 - loss: 0.4114
Epoch 24/30
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8583 - loss: 0.4089
Epoch 25/30
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8597 - loss: 0.4064
Epoch 26/30
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8608 - loss: 0.4042
Epoch 27/30
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8618 - loss: 0.4020
Epoch 28/30
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8628 - loss: 0.3999
Epoch 29/30
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8638 - loss: 0.3980
Epoch 30/30
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8648 - loss: 0.3961
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

[I 2026-10-17 10:24:23,851] Trial 7 finished with value: 0.879255400643481 and parameters: {'epochs': 30, 'batch_size': 58, 'units_layer1': 30, 'units_layer2': 21, 'optimizer': 'adam', 'learning_rate': 0.0008737649331481577}. Best is trial 3 with value: 0.8919871303814922.

Epoch 1/50

C:\Users\aksta\AppData\Local\Temp\ipykernel_32492\1466992178.py:12: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 1e-2)

149/149 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - AUC: 0.6353 - loss: 0.6198
Epoch 2/50
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7182 - loss: 0.5887
Epoch 3/50
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7427 - loss: 0.5751
Epoch 4/50
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7624 - loss: 0.5600
Epoch 5/50
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7781 - loss: 0.5410
Epoch 6/50
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7903 - loss: 0.5218
Epoch 7/50
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 997us/step - AUC: 0.8006 - loss: 0.5049
Epoch 8/50
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8092 - loss: 0.4903
Epoch 9/50
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8164 - loss: 0.4776
Epoch 10/50
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8225 - loss: 0.4672
Epoch 11/50
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8275 - loss: 0.4585
Epoch 12/50
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8318 - loss: 0.4504
Epoch 13/50
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 995us/step - AUC: 0.8355 - loss: 0.4428
Epoch 14/50
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8388 - loss: 0.4359
Epoch 15/50
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8416 - loss: 0.4296
Epoch 16/50
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8441 - loss: 0.4239
Epoch 17/50
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8466 - loss: 0.4184
Epoch 18/50
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8487 - loss: 0.4133
Epoch 19/50
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8512 - loss: 0.4088
Epoch 20/50
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8533 - loss: 0.4049
Epoch 21/50
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8551 - loss: 0.4014
Epoch 22/50
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8571 - loss: 0.3983
Epoch 23/50
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8587 - loss: 0.3955
Epoch 24/50
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8601 - loss: 0.3929
Epoch 25/50
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8614 - loss: 0.3905
Epoch 26/50
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8628 - loss: 0.3883
Epoch 27/50
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8640 - loss: 0.3864
Epoch 28/50
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8653 - loss: 0.3847
Epoch 29/50
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8664 - loss: 0.3832
Epoch 30/50
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8674 - loss: 0.3817
Epoch 31/50
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8682 - loss: 0.3805
Epoch 32/50
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8691 - loss: 0.3792
Epoch 33/50
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8704 - loss: 0.3779
Epoch 34/50
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8711 - loss: 0.3767
Epoch 35/50
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8720 - loss: 0.3755
Epoch 36/50
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8728 - loss: 0.3743
Epoch 37/50
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8735 - loss: 0.3734
Epoch 38/50
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8743 - loss: 0.3724
Epoch 39/50
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8751 - loss: 0.3715
Epoch 40/50
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8759 - loss: 0.3705
Epoch 41/50
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8764 - loss: 0.3697
Epoch 42/50
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8770 - loss: 0.3689
Epoch 43/50
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8772 - loss: 0.3681
Epoch 44/50
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8780 - loss: 0.3672
Epoch 45/50
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8784 - loss: 0.3664
Epoch 46/50
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8790 - loss: 0.3658
Epoch 47/50
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8796 - loss: 0.3651
Epoch 48/50
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8802 - loss: 0.3644
Epoch 49/50
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8810 - loss: 0.3635
Epoch 50/50
149/149 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8817 - loss: 0.3629
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

[I 2026-10-17 10:24:34,917] Trial 8 finished with value: 0.8838210510188447 and parameters: {'epochs': 50, 'batch_size': 25, 'units_layer1': 16, 'units_layer2': 9, 'optimizer': 'adam', 'learning_rate': 0.0009328463484586444}. Best is trial 3 with value: 0.8919871303814922.

Epoch 1/31

C:\Users\aksta\AppData\Local\Temp\ipykernel_32492\1466992178.py:12: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 1e-2)

71/71 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - AUC: 0.4011 - loss: 0.6967
Epoch 2/31
71/71 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.5056 - loss: 0.6561
Epoch 3/31
71/71 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.6203 - loss: 0.6281
Epoch 4/31
71/71 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.6725 - loss: 0.6094
Epoch 5/31
71/71 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.6941 - loss: 0.5956
Epoch 6/31
71/71 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7079 - loss: 0.5851
Epoch 7/31
71/71 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7184 - loss: 0.5767
Epoch 8/31
71/71 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7273 - loss: 0.5695
Epoch 9/31
71/71 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7344 - loss: 0.5632
Epoch 10/31
71/71 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7408 - loss: 0.5573
Epoch 11/31
71/71 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7467 - loss: 0.5519
Epoch 12/31
71/71 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7520 - loss: 0.5469
Epoch 13/31
71/71 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7569 - loss: 0.5419
Epoch 14/31
71/71 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7615 - loss: 0.5369
Epoch 15/31
71/71 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7671 - loss: 0.5320
Epoch 16/31
71/71 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7727 - loss: 0.5272
Epoch 17/31
71/71 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7778 - loss: 0.5225
Epoch 18/31
71/71 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7823 - loss: 0.5179
Epoch 19/31
71/71 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7861 - loss: 0.5135
Epoch 20/31
71/71 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7894 - loss: 0.5092
Epoch 21/31
71/71 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7929 - loss: 0.5050
Epoch 22/31
71/71 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7958 - loss: 0.5010
Epoch 23/31
71/71 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7985 - loss: 0.4972
Epoch 24/31
71/71 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8007 - loss: 0.4937
Epoch 25/31
71/71 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8031 - loss: 0.4903
Epoch 26/31
71/71 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8048 - loss: 0.4872
Epoch 27/31
71/71 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8066 - loss: 0.4844
Epoch 28/31
71/71 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8081 - loss: 0.4817
Epoch 29/31
71/71 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8095 - loss: 0.4792
Epoch 30/31
71/71 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8110 - loss: 0.4767
Epoch 31/31
71/71 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8123 - loss: 0.4743
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

[I 2026-10-17 10:24:39,748] Trial 9 finished with value: 0.8398243194933864 and parameters: {'epochs': 31, 'batch_size': 53, 'units_layer1': 15, 'units_layer2': 9, 'optimizer': 'rmsprop', 'learning_rate': 0.0005136449402696853}. Best is trial 3 with value: 0.8919871303814922.

Best trial: 0.8919871303814922
Best hyperparameters: {'epochs': 48, 'batch_size': 63, 'units_layer1': 29, 'units_layer2': 13, 'optimizer': 'adam', 'learning_rate': 0.0013669388891433209}

{'epochs': 48,
 'batch_size': 63,
 'units_layer1': 29,
 'units_layer2': 13,
 'optimizer': 'adam',
 'learning_rate': 0.0013669388891433209}

# 7. Train and evaluate the final model with the best hyperparameters

In [7]:
# Train the final model with the best hyperparameters

best_model = Sequential()
best_model.add(Dense(units=best_params['units_layer1'], activation='relu'))
best_model.add(Dense(units=best_params['units_layer2'], activation='relu'))
best_model.add(Dense(1, activation='sigmoid'))

if best_params['optimizer'] == 'adam':
    best_optimizer = Adam(learning_rate=best_params['learning_rate'])
elif best_params['optimizer'] == 'sgd':
    best_optimizer = SGD(learning_rate=best_params['learning_rate'])
elif best_params['optimizer'] == 'rmsprop':
    best_optimizer = RMSprop(learning_rate=best_params['learning_rate'])
elif best_params['optimizer'] == 'adagrad':
    best_optimizer = Adagrad(learning_rate=best_params['learning_rate'])

best_model.compile(optimizer=best_optimizer, loss='binary_crossentropy', metrics=['AUC'])


def evaluate(model, X_train, y_train, X_test, y_test):
    
    model.fit(X_train, y_train, epochs=best_params['epochs'], batch_size=best_params['batch_size'])
    
    '''Predictions and probabilities for the training set'''
    
    y_train_prob = model.predict(X_train)

    '''Predictions and probabilities for the test set'''
    
    y_test_prob = model.predict(X_test)

    '''Calculate metrics for the training set''' 
    
    roc_train_prob = roc_auc_score(y_train, y_train_prob)
    gini_train_prob = roc_train_prob * 2 - 1
    

    '''Calculate metrics for the test set'''
    
    roc_test_prob = roc_auc_score(y_test, y_test_prob)
    gini_test_prob = roc_test_prob * 2 - 1
    

    results = pd.DataFrame({
        'Dataset': ['Train', 'Test'],
        'Gini': [gini_train_prob * 100, gini_test_prob * 100],
    
    })

    return results


evaluate(best_model, X_train_scaled, y_train, X_test_scaled, y_test)

Epoch 1/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - AUC: 0.6419 - loss: 0.6257
Epoch 2/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7424 - loss: 0.5561
Epoch 3/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7660 - loss: 0.5311
Epoch 4/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7833 - loss: 0.5113
Epoch 5/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.7974 - loss: 0.4951
Epoch 6/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8105 - loss: 0.4807
Epoch 7/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8204 - loss: 0.4690
Epoch 8/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8264 - loss: 0.4596
Epoch 9/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8317 - loss: 0.4515
Epoch 10/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8362 - loss: 0.4438
Epoch 11/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8402 - loss: 0.4370
Epoch 12/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8438 - loss: 0.4308
Epoch 13/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8469 - loss: 0.4253
Epoch 14/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8495 - loss: 0.4204
Epoch 15/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8520 - loss: 0.4160
Epoch 16/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8543 - loss: 0.4121
Epoch 17/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8568 - loss: 0.4082
Epoch 18/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8588 - loss: 0.4046
Epoch 19/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8607 - loss: 0.4012
Epoch 20/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8624 - loss: 0.3982
Epoch 21/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8642 - loss: 0.3953
Epoch 22/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8656 - loss: 0.3925
Epoch 23/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8669 - loss: 0.3901
Epoch 24/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8683 - loss: 0.3877
Epoch 25/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8696 - loss: 0.3856
Epoch 26/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8707 - loss: 0.3837
Epoch 27/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8716 - loss: 0.3820
Epoch 28/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8729 - loss: 0.3802
Epoch 29/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8736 - loss: 0.3785
Epoch 30/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8744 - loss: 0.3771
Epoch 31/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8753 - loss: 0.3756
Epoch 32/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8760 - loss: 0.3743
Epoch 33/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8767 - loss: 0.3730
Epoch 34/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8773 - loss: 0.3719
Epoch 35/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8780 - loss: 0.3707
Epoch 36/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8788 - loss: 0.3696
Epoch 37/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8791 - loss: 0.3685
Epoch 38/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8799 - loss: 0.3675
Epoch 39/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8804 - loss: 0.3665
Epoch 40/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8810 - loss: 0.3655
Epoch 41/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8814 - loss: 0.3647
Epoch 42/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8818 - loss: 0.3638
Epoch 43/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8823 - loss: 0.3630
Epoch 44/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8828 - loss: 0.3623
Epoch 45/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8834 - loss: 0.3614
Epoch 46/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8839 - loss: 0.3607
Epoch 47/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8841 - loss: 0.3600
Epoch 48/48
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - AUC: 0.8845 - loss: 0.3594
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 791us/step
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step

  Dataset       Gini
0   Train  77.823828
1    Test  77.351514